name: build-env
channels:
  - conda-forge
dependencies:
  - python
  - pip
  - jupyter_server
  - jupyterlab-night
  - jupyterlab_miami_nights
  - jupyterlab-filesystem-access
  - jupyterlite-core
  - jupyterlite-xeus
  - jupyterlab-language-pack-ja-JP
  - jupyterlab-language-pack-zh-CN
  - ipywidgets
  - ipyvuetify