on:
  workflow_dispatch:

jobs:
  deploy-pages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - run: |
          python -m pip install requirements-dev.txt --upgrade
          bash compile_requirements.sh
          python download_wasm32_wheels.py
          bash pwa_build.sh
          python patch_html.py
      - uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: dist