on:
  workflow_dispatch:

jobs:
  deploy-pages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: mamba-org/setup-micromamba@v2
        with:
          environment-file: build-environment.yml
          init-shell: >-
            bash
          cache-environment: true
          post-cleanup: 'all'
      - name: Build
        shell: bash -el {0}
        run: |
          jupyter lite build
      - uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: dist